# action.yml
name: "krew-release-bot"
description: "automatically opens PR for upstream krew-index repo when you publish new release of your awesome plugin"
inputs:
  workdir:
    description: "Working directory, defaults to env.GITHUB_WORKSPACE"
  krew_template_file:
    description: "the path to template file relative to $workdir. e.g. templates/misc/plugin-name.yaml. defaults to .krew.yaml"
runs:
  using: "docker"
  image: "docker://armandomeeuwenoord/krew-release-bot:v1.0.0"
# 
